import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import { ThemeProvider } from "./components/ThemeProvider";
import { Header } from "./components/Header";
import { cookies } from "next/headers";
import { auth } from "@repo/common";
import prisma from "@repo/db";

async function getUser() {
  const cookieStore = await cookies();
  const token = cookieStore.get("token")?.value;

  if (!token) return null;

  const result = auth.verifyTokenSafe(token);
  if (!result.valid) return null;

  const user = await prisma.user.findUnique({
    where: { id: result.id },
    select: { id: true, name: true, email: true }
  });
  return user;
}

function getInitials(name: string): string {
  return name
    .split(" ")
    .map((n) => n[0])
    .join("")
    .toUpperCase()
    .slice(0, 2);
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const user = await getUser();
  const initials = user ? getInitials(user.name || "U") : null;

  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${geistSans.variable} ${geistMono.variable} bg-white text-black dark:bg-[#0a0a0a] dark:text-white transition-colors antialiased`}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <Header user={user} initials={initials} />
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
